export { MainPage } from './MainPage'
export { GenresPage } from './GenresPage'
export { DetailGenrePage } from './DetailGenrePage'
export { FilmPage } from './FilmPage'
export { AccountPage } from './AccountPage'
